name: inventory_management_system_server
description: Server for the inventory management system.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: 2.6.0
  crypto: ^3.0.1
  http: ^1.1.0
  connectivity_plus: 3.0.3
  
dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: ^1.24.0
  serverpod_test: 2.6.0
  serverpod_cli: 2.6.0

